// examples/components/angular/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  OnDestroy,
  OnInit,
} from '@angular/core';
import '@esri/calcite-components/dist/components/calcite-button';
import '@esri/calcite-components/dist/components/calcite-icon';
import '@esri/calcite-components/dist/components/calcite-loader';
import '@esri/calcite-components/dist/components/calcite-slider';

@Component({
  selector: 'app-root',
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'calcite-components-angular-example';
  sliderValue = 50;

  public isLoading: boolean = true;

  ngOnInit() {
    this.fetch();
  }

  ngOnDestroy(): void {
    this.clearSliderValue();
  }

  async fetch() {
    await new Promise((r) => setTimeout(r, 2000));
    this.isLoading = false;
  }

  onSliderInput(event: Event) {
    const value = (event.target as HTMLCalciteSliderElement).value;
    if (typeof value === 'number') {
      this.sliderValue = value;
    }
  }

  clearSliderValue() {
    this.sliderValue = 0;
  }
}

<div *ngIf="isLoading; else content">
  <calcite-loader label="Loading..."></calcite-loader>
</div>

<ng-template #content>
  <h1>
    Calcite Components Angular Example
    <calcite-icon icon="banana"></calcite-icon>
  </h1>

  <calcite-slider
    min="1"
    max="100"
    [value]="sliderValue"
    (calciteSliderInput)="onSliderInput($event)"
  ></calcite-slider>

  <p>The slider currently has a value of {{ sliderValue }}.</p>

  <calcite-button (click)="clearSliderValue()">Clear</calcite-button>
</ng-template>

// examples/components/react/src/App.tsx
import { useState } from "react";
import "@esri/calcite-components/dist/components/calcite-button";
import "@esri/calcite-components/dist/components/calcite-icon";
import "@esri/calcite-components/dist/components/calcite-slider";
import { CalciteButton, CalciteIcon, CalciteSlider } from "@esri/calcite-components-react";
import "./App.css";

function App() {
  const [sliderValue, setSliderValue] = useState(50);

  return (
    <>
      <h1>
        Hello, React <CalciteIcon icon="banana" />
      </h1>
      <CalciteButton onClick={() => setSliderValue(0)}>Reset</CalciteButton>
      <CalciteSlider
        min={1}
        max={100}
        value={sliderValue}
        step={1}
        onCalciteSliderInput={({ target }) => {
          const value = (target as HTMLCalciteSliderElement).value;
          if (typeof value === "number") {
            setSliderValue(value);
          }
        }}
      />
      <p>The slider currently has a value of {sliderValue}</p>
    </>
  );
}

export default App;
