// examples/components/angular/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'calcite-components-angular-example';
  sliderValue = 50;

  public isLoading: boolean = true;

  ngOnInit() {
    this.fetch();
  }

  ngOnDestroy(): void {
    this.clearSliderValue();
  }

  async fetch() {
    await new Promise((r) => setTimeout(r, 2000));
    this.isLoading = false;
  }

  onSliderInput(event: Event) {
    const value = (event.target as HTMLCalciteSliderElement).value;
    if (typeof value === 'number') {
      this.sliderValue = value;
    }
  }

  clearSliderValue() {
    this.sliderValue = 0;
  }
}

<div *ngIf="isLoading; else content">
  <calcite-loader label="Loading..."></calcite-loader>
</div>

<ng-template #content>
  <h1>
    Calcite Components Angular Example
    <calcite-icon icon="banana"></calcite-icon>
  </h1>

  <calcite-slider
    min="1"
    max="100"
    [value]="sliderValue"
    (calciteSliderInput)="onSliderInput($event)"
  ></calcite-slider>

  <p>The slider currently has a value of {{ sliderValue }}.</p>

  <calcite-button (click)="clearSliderValue()">Clear</calcite-button>
</ng-template>

// examples/components/react-19-and-above/src/App.tsx
import { useState } from "react";
import "@esri/calcite-components/components/calcite-button";
import "@esri/calcite-components/components/calcite-icon";
import "@esri/calcite-components/components/calcite-slider";
import "./App.css";

function App() {
  const [sliderValue, setSliderValue] = useState(50);

  const handleSliderInput = (event: CustomEvent) => {
    const value = (event.target as HTMLCalciteSliderElement).value;
    if (typeof value === "number") {
      setSliderValue(value);
    }
  };

  return (
    <>
      <h1>
        Hello, React <calcite-icon icon="banana" />
      </h1>
      <calcite-button onClick={() => setSliderValue(0)}>Reset</calcite-button>
      <calcite-slider
        min={1}
        max={100}
        value={sliderValue}
        step={1}
        oncalciteSliderInput={handleSliderInput}
      />
      <p>The slider currently has a value of {sliderValue}.</p>
    </>
  );
}

export default App;
